### ISSUE TITLE
DOI for citing the guideline using Zenodo

### ISSUE THREAD

**Issue by benediktschwab** [tum-gis/road2citygml3#2]
Could the creation of a DOI make it simpler to reference this guideline in scientific articles?
[Zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content) also provides a DOI for all versions (see 'Cite all versions' at [this example](https://zenodo.org/record/7761085) and the [docs](https://help.zenodo.org/#versioning)).

**Comment by thomashkolbe** [comment]
Good idea!

**Comment by ChBeil** [comment]
Created DOI using Zenodo and added citation recommendation to document and github page.
